// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVESqZngEs690XRqVUUmNB0gr-IDSW4co',
    appId: '1:293500240654:web:4e6fc3e20d4c52424e8d5f',
    messagingSenderId: '293500240654',
    projectId: 'prueba-tecnica-dashfleet',
    authDomain: 'prueba-tecnica-dashfleet.firebaseapp.com',
    storageBucket: 'prueba-tecnica-dashfleet.appspot.com',
    measurementId: 'G-YJTKWBF3JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkf4wGob77oD-PEm6K29I66mFbguKFmI8',
    appId: '1:293500240654:android:5985cff6cc4e2b444e8d5f',
    messagingSenderId: '293500240654',
    projectId: 'prueba-tecnica-dashfleet',
    storageBucket: 'prueba-tecnica-dashfleet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ4aSEC3m3YHN8pljVpmJIERAgRbq7oRE',
    appId: '1:293500240654:ios:0353b2366f10f0124e8d5f',
    messagingSenderId: '293500240654',
    projectId: 'prueba-tecnica-dashfleet',
    storageBucket: 'prueba-tecnica-dashfleet.appspot.com',
    iosClientId: '293500240654-ad79pltr2hqlprvufdmaqrp18h56osgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaTecnica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ4aSEC3m3YHN8pljVpmJIERAgRbq7oRE',
    appId: '1:293500240654:ios:0353b2366f10f0124e8d5f',
    messagingSenderId: '293500240654',
    projectId: 'prueba-tecnica-dashfleet',
    storageBucket: 'prueba-tecnica-dashfleet.appspot.com',
    iosClientId: '293500240654-ad79pltr2hqlprvufdmaqrp18h56osgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaTecnica',
  );
}
